import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-data-grid/lib/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import Script from "next/script";

export const metadata = {
  title: "ChAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* jQuery must load first */}
        <Script src="https://code.jquery.com/jquery-3.7.1.min.js" strategy="lazyOnload" />

        {/* DataTables core */}
        <Script src="https://cdn.datatables.net/2.3.7/js/dataTables.min.js" strategy="lazyOnload" />
        <Script src="https://cdn.datatables.net/2.3.7/js/dataTables.bootstrap5.min.js" strategy="lazyOnload" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
